-- Rename ShiftType enum values
ALTER TYPE "ShiftType" RENAME VALUE 'TWELVE_HOURS' TO 'TWELVE_DAY';
ALTER TYPE "ShiftType" RENAME VALUE 'NIGHT' TO 'TWELVE_NIGHT';
ALTER TYPE "ShiftType" RENAME VALUE 'TWENTY_FOUR_HOURS' TO 'TWENTY_FOUR';

-- Add new value
ALTER TYPE "ShiftType" ADD VALUE 'TWENTY_FOUR_INVERTED';
